/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LavoriRouteImport } from './routes/lavori'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LavoriRoute = LavoriRouteImport.update({
  id: '/lavori',
  path: '/lavori',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/atelier': typeof AtelierRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/lavori': typeof LavoriRoute
  '/privacy': typeof PrivacyRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/atelier': typeof AtelierRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/lavori': typeof LavoriRoute
  '/privacy': typeof PrivacyRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/atelier': typeof AtelierRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/lavori': typeof LavoriRoute
  '/privacy': typeof PrivacyRoute
  '/servizi': typeof ServiziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/atelier'
    | '/contatti'
    | '/cookie'
    | '/lavori'
    | '/privacy'
    | '/servizi'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/atelier'
    | '/contatti'
    | '/cookie'
    | '/lavori'
    | '/privacy'
    | '/servizi'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/atelier'
    | '/contatti'
    | '/cookie'
    | '/lavori'
    | '/privacy'
    | '/servizi'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AtelierRoute: typeof AtelierRoute
  ContattiRoute: typeof ContattiRoute
  CookieRoute: typeof CookieRoute
  LavoriRoute: typeof LavoriRoute
  PrivacyRoute: typeof PrivacyRoute
  ServiziRoute: typeof ServiziRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lavori': {
      id: '/lavori'
      path: '/lavori'
      fullPath: '/lavori'
      preLoaderRoute: typeof LavoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AtelierRoute: AtelierRoute,
  ContattiRoute: ContattiRoute,
  CookieRoute: CookieRoute,
  LavoriRoute: LavoriRoute,
  PrivacyRoute: PrivacyRoute,
  ServiziRoute: ServiziRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
